### PR TITLE
Test

### PR DESCRIPTION
**Pull request by ndush**

### CODE REVIEW

**Comment by ccanyanwu** [comment]
Remove the full stop at the end of your output

**Comment by ndush** [comment]
Done and PRd

**Comment by ccanyanwu** [comment]
Okay

**Comment by ndush** [comment]
This branch has conflicts that must be resolvedOnly those with write access
<https://help.github.com/articles/what-are-the-different-access-permissions> to
this repository can merge pull requests.
I hope this aint an issue

**Comment by ccanyanwu** [comment]
It's still an issue

**Comment by ndush** [comment]
Kindly help me on how to resolve this issue

**Comment by ndush** [comment]
I have done the process afresh like four times. Which is the easiest way to
resolve this

**Comment by ccanyanwu** [comment]
Talk to me on slack

**Pull request closed without merging**
