### PR TITLE
torohscript

### PR DESCRIPTION
**Pull request by etojama**

### CODE REVIEW

**Comment by Elvislogan** [comment]
Please follow the output format on the readme of this project or on the slack chann

**Comment by codeddave** [comment]
Your output will not account for spaces between some of the words. You should add empty strings " " in between some words

**Comment by etojama** [comment]
David, I honestly don't understand you please. Can you show my by picture
how not to account for spaces or putting empty strings?

Thanks

**Comment by codeddave** [comment]
the way you wrote your output, there wont be spaces between some of the words and the variables that come after them. 
 you need to add spaces between them by adding  empty strings, " " between them.

**Comment by etojama** [comment]
Ok. The problem is only in my output and the spaces right? If you don't
mind, can you point out the places I need more space and that I can add
empty strings between them.

**Comment by codeddave** [comment]
message me on slack @daveisking

**Pull request closed without merging**
